Integrate sdctl
sdcio/docs pull request #41
Opened 2024-02-26 15:05 UTC by hansthienpondt

2024-02-26 15:09 UTC, steiler commented on .github/workflows/docs.yml
> +          cat docs/user-guide/troubleshooting.md | envsubst > docs/user-guide/troubleshooting.md
shall we better go from md.tmpl to .md. otherwise you run this locallly and then the changed template might be gone ...

2024-02-26 15:12 UTC, steiler requested changes

2024-02-29 08:28 UTC, hansthienpondt commented on .github/workflows/docs.yml
> +          cat docs/user-guide/troubleshooting.md | envsubst > docs/user-guide/troubleshooting.md
done, renamed file and added a manual step in Makefile to be able to generate this locally.

2024-02-29 12:24 UTC, steiler commented
@hansthienpondt there is merge conflict thats needs be to be resolved.

2024-02-29 13:16 UTC, hansthienpondt commented
Whoops, prematurely asked for a review!

2024-02-29 15:56 UTC, merged